apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: e-learning
data:
  application.yml: |
    server:
      port: 8080
      
    spring:
      application:
        name: api-gateway
      cloud:
        gateway:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2
                
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=2
                
            - id: course-service
              uri: lb://course-service
              predicates:
                - Path=/api/courses/**
              filters:
                - StripPrefix=2
                
            - id: video-service
              uri: lb://video-service
              predicates:
                - Path=/api/videos/**
              filters:
                - StripPrefix=2
      
      # Configure service discovery with Kubernetes
      cloud:
        kubernetes:
          discovery:
            all-namespaces: false
      
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always
      metrics:
        export:
          prometheus:
            enabled: true
      tracing:
        sampling:
          probability: 1.0
          
    logging:
      pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: e-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: ${DOCKER_REGISTRY:-localhost:5000}/api-gateway:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: common-config
        volumeMounts:
        - name: api-gateway-config
          mountPath: /workspace/config
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
      volumes:
      - name: api-gateway-config
        configMap:
          name: api-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: e-learning
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 