package com.hasandag.aiservice.provider;

import com.hasandag.aiservice.dto.AiRequest;
import com.hasandag.aiservice.dto.AiResponse;
import com.hasandag.aiservice.util.Logger;
import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

@Component
public class CopilotProvider implements AiProvider {
    private static final org.slf4j.Logger log = Logger.getLogger(CopilotProvider.class);

    @Value("${ai.provider:openai}")
    private String activeProvider;

    @Value("${copilot.api.key:default-key}")
    private String apiKey;

    @Value("${copilot.api.url:https://api.githubcopilot.com/chat/completions}")
    private String apiUrl;

    @Value("${copilot.api.model:gpt-4}")
    private String model;

    @Value("${copilot.api.timeout:60}")
    private int timeout;

    private WebClient webClient;

    @PostConstruct
    public void init() {
        this.webClient = WebClient.builder()
                .baseUrl(apiUrl)
                .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                .defaultHeader("Authorization", "Bearer " + apiKey)
                .build();
        log.debug("Initialized Copilot provider with URL: {}, model: {}", apiUrl, model);
    }

    @Override
    public boolean isActive() {
        return "copilot".equalsIgnoreCase(activeProvider);
    }

    @Override
    public AiResponse processQuestion(AiRequest request) {
        log.info("Processing question with Copilot provider: {}", request.getQuestion());

        try {
            // For initial implementation - return a mock response until we can properly integrate with Copilot API
            String mockAnswer = "This is a response from the GitHub Copilot provider. " +
                    "Your question was: " + request.getQuestion();
            
            return AiResponse.builder()
                    .answer(mockAnswer)
                    .questionId(UUID.randomUUID().toString())
                    .timestamp(LocalDateTime.now())
                    .sourceReferences("Generated by GitHub Copilot")
                    .courseId(request.getCourseId())
                    .userId(request.getUserId())
                    .success(true)
                    .build();
                
            /* Actual implementation to be completed later
            String question = addContextToQuestion(request);

            Map<String, Object> message = new HashMap<>();
            message.put("role", "user");
            message.put("content", question);

            Map<String, Object> requestBody = new HashMap<>();
            requestBody.put("model", model);
            requestBody.put("messages", new Object[]{message});
            requestBody.put("temperature", 0.7);
            requestBody.put("max_tokens", 800);

            CopilotResponse copilotResponse = webClient.post()
                    .bodyValue(requestBody)
                    .retrieve()
                    .bodyToMono(CopilotResponse.class)
                    .timeout(Duration.ofSeconds(timeout))
                    .block();

            String answer = extractAnswer(copilotResponse);

            return AiResponse.builder()
                    .answer(answer)
                    .questionId(UUID.randomUUID().toString())
                    .timestamp(LocalDateTime.now())
                    .sourceReferences("Generated by GitHub Copilot")
                    .courseId(request.getCourseId())
                    .userId(request.getUserId())
                    .success(true)
                    .build();
            */
        } catch (Exception e) {
            log.error("Failed to process Copilot request: {}", e.getMessage(), e);
            return AiResponse.builder()
                    .success(false)
                    .errorMessage("Failed to process Copilot request: " + e.getMessage())
                    .timestamp(LocalDateTime.now())
                    .build();
        }
    }

    private String addContextToQuestion(AiRequest request) {
        StringBuilder questionWithContext = new StringBuilder();
        
        questionWithContext.append("You are an educational AI assistant helping with programming and technology questions.\n\n");
        
        if (request.getCourseId() != null && !request.getCourseId().isEmpty()) {
            questionWithContext.append("For course ID: ").append(request.getCourseId()).append("\n\n");
        }
        
        if (request.getContext() != null && !request.getContext().isEmpty()) {
            questionWithContext.append("Context: ").append(request.getContext()).append("\n\n");
        }
        
        questionWithContext.append("Question: ").append(request.getQuestion());
        
        return questionWithContext.toString();
    }

    private String extractAnswer(CopilotResponse response) {
        if (response == null || response.choices == null || response.choices.length == 0) {
            return "No response from Copilot";
        }
        
        return response.choices[0].message.content;
    }

    // Response classes for JSON deserialization
    private static class CopilotResponse {
        private Choice[] choices;
    }
    
    private static class Choice {
        private Message message;
    }
    
    private static class Message {
        private String content;
    }
} 